### PR TITLE
Adding Laced and Edged genes

### PR DESCRIPTION
**Pull request by Oddlybird**
According to a forum thread, both are common rarity.  AH prices are hovering around 140K / 120K, tooltip says they only cost 14K/12K.  Can't find them in the marketplace to verify prices.

Sorted a few things in fr_data.js, to find them easier.  I can resubmit without those changes if preferred.
@JiYouMCC Hello again!

### CODE REVIEW

**Comment by JiYouMCC** [comment]
There's some conflict in the pull request. I'll try to create another PR to do this tonight(8-10 hours later)
Also I'll ask friends about the translation of the new genes. :)

lanced 鸡毛
edged 鸡翅

**Comment by Oddlybird** [comment]
@JiYouMCC Is there anything I could do to help?

**Comment by JiYouMCC** [comment]
There's something busy on working recently.
If you have time, you can do following:

1. In your own repository, merge code from my repository first.
2. Do the code change
3. Create pull request.

If it is too complicated, you can wait. I'll try to do it in a lunch break.

Sorry for delay.

Oddbird <notifications@github.com> 于2019年5月12日周日 上午12:58写道：

**Comment by JiYouMCC** [comment]
@Oddlybird The changes have been merged from another 2 pull requests. You can check if they work.

But I remember the order of the gene should be the same as FR checklist(I'm not sure.) Now they are ordered by alphabet, is that OK?

**Pull request closed without merging**
