### PR TITLE
Update the UI to fit in without as much scrolling

### PR DESCRIPTION
**Pull request by fictivecreations**
Updates made to the breeding tool page's layout for margin/padding/overall spacing to allow for more of the elements to fit into the screen without having to scroll for overall ease of use.

Also gave some elements a little more room so they wouldn't cut off the text.

Also updated the color css so it wouldn't be overridden by the dropdown's default css.

### CODE REVIEW

**Review by JiYouMCC — APPROVED** [review]
The UI in mobile maybe not so prefect, but looks better than before. Thank you!

**Comment by JiYouMCC** [comment]
@sunlanterns  What's your ID in FR? Maybe add as friend?

**Comment by fictivecreations** [comment]
@JiYouMCC Sorry for the late response! I'd love to be, I reached out in-game.

**Comment by JiYouMCC** [comment]
close #143

**Pull request merged**
